magnusbaeck/logstash-filter-verifier

README.md

Syntax error corrected in sample.

---

Makefile

As of `go help gopath` the `GOPATH` environment variable supports a list of places to look for Go code.

Support multiple directories in GOPATH

---

README.md
logstash/fieldset.go
logstash/fieldset_test.go

Nested fields (values of object type) are addressed in Logstash with
field reference notation ([1]). The nested field names are put into square
brackets [], starting on the top level. If a top level field is addressed,
the square brackets might be omited.
Currently values of object type are not allowed in arrays.
Fixes #12
[1]: https://www.elastic.co/guide/en/logstash/current/event-dependent-configuration.html#logstash-config-field-references

Add support for value of object type

---

Godeps
testcase/testcase.go

Does include line number and context in error message.

Better error reporting on JSON syntax errors

---

logstash/configfiledir.go
logstash/fieldset.go
logstash/fieldset_test.go

Large floats must not be converted to exponential notation, because this is not valid for Logstash
https://github.com/elastic/logstash/blob/master/logstash-core/lib/logstash/config/grammar.treetop#L92
Better error message, if copy of config fails.

Handling large floats

---

README.md

Migrate test case files from old to new format using the
`jq` command.

Added migration instructions for test case json

---

.travis.yml
README.md
logstash-filter-verifier.go
logstash/main_test.go
logstash/parallel_process.go
logstash/parallel_process_test.go
logstash/result.go

Implements the usage of logstash-input-unix as input, which
allows to use a single Logstash instance for the execution
of multiple test case files, which greatly shortens the
duration for the test execution.
To enable this feature, run logstash-filter-verifier with the
command line flage `--sockets`.
This feature does only work on systems, which do support
unix domain sockets.
The logstash-input-unix plugins adds the two fields `host` and
`path`. Therefore these fields should be ignored in the test cases.
This implementation does need at least Go 1.8beta1, as the function
net.SetUnlinkOnClose is used, which is introduced with Go 1.8.
Fixes #14 
May help for #11

Parallel execution of multiple test cases

---

README.md
testcase/testcase.go
testcase/testcase_test.go

recommend `json_lines` instead of `json`
to support the unix domain socket mode, without the
need to modify the test cases.
Fixes #24

Changed default codec from `plain` to `line`

---

logstash-filter-verifier.go

error strings should not be capitalized or end with punctuation or a newline (golint)

Fix linter error

---

logstash-filter-verifier.go

Adds flag `--sockets-timeout` to allow to modify the timeout
on the unix domain sockets (default: 60s).
Fixes: #32

Make timeout for unix domain sockets a flag

---

logstash/fieldset.go
logstash/fieldset_test.go

JSON unmarshal never produces ints but only float64, therefore no special
handling of ints is necessary.
Closes #20

Remove dead code for handling ints from JSON

---

Godeps
logstash/invocation_test.go
logstash/pipelineconfigdir.go
logstash/pipelineconfigdir_test.go
testhelpers/compare.go

This RP automatically removes the input and output config sections when copying over the logstash config file(s), which will allow testing the actual configuration that is being used.
Ref #10

Remove the input and output config sections

---

.gitignore
README.md
go.mod
go.sum
testcase/discover.go
testcase/discover_test.go
testcase/helper.go
testcase/helper_test.go
testcase/testcase.go
testcase/testcase_test.go

Add some enhances:
- Add test case YAML support and keep JSON support
- Add dot notation in exclude fields to excludes sub fields like `log.file.path`
- Add dot notation in fields to write test in easy way: `"log.file.path": "/tmp/test.log"` is equivalent to `"log": {"file": {"path": "/tmp/test.log"}}`.
- Add dot notation in input when use `json_lines` codecs to write test in easy way: `{"log.file.path": "/tmp/test.log"}` is equivalent to `{"log": {"file": {"path": "/tmp/test.log"}}}`.
I add some unit test and fix readme.

Add YAML support and dot notation for fields, exclude and input

---

logstash-filter-verifier.go

Do not check that Logstash path is an executable file if OS is windows.
Fix issue #71

Fix Windows compatibility

---

README.md
go.mod
testcase/helper.go
testcase/helper_test.go
testcase/testcase.go
testcase/testcase_test.go

Remove dot notation support and keep only bracket notation for inputs, excludes and fields

Remove dot notation, support only bracket notation

---

logstash/parallel_process.go
logstash/parallel_process_test.go
logstash/process.go

This enables codecs that need additional configuration settings, like
`multiline` with an escaped string:
```
codec: "multiline {
pattern => \"^%{YEAR}/%{MONTHNUM}/%{MONTHDAY}[T ]%{HOUR}:?%{MINUTE}:?%{SECOND}\"
negate => true
what => previous
}"
```

Insert codec as a string, not as a single-quoted character literal.

---

README.md

Using the example file leads to an error otherwise:
```
Error reading/unmarshalling testcases.yml: yaml: line 15: found character that cannot start any token
```

README.md: quote @timestamp in yaml example

---

internal/app/app.go
internal/app/standalone.go

@magnusbaeck I am not sure, if `$HOME/.logstash-filter-verifier` is a good choice for the config file. I took this from the [examples of spf13/viper](https://pkg.go.dev/github.com/spf13/viper#readme-reading-config-files). Personally I think it would be better to use the directory from [os.UserConfigDir](https://golang.org/pkg/os/#UserConfigDir) and add the application name to it, like this:
```Go
configDir, err := os.UserHomeDir()
if err == nil {
viper.AddConfigPath(path.Join(configDir, "logstash-filter-verifier"))
}
```
What do you think?

Small fixes

---

go.mod
go.sum
integration_test.go
internal/app/daemon/run/run.go
internal/app/daemon_run.go
internal/daemon/filtermock/filtermock.go
internal/daemon/logstashconfig/file.go
internal/daemon/pipeline/pipeline.go
internal/daemon/pipeline/pipeline_test.go
testdata/filtermock.yml
testdata/filtermock/filtermock.conf
testdata/mocks/filtermock.yml
testdata/testcases/filtermock/filtermock.json

Implementation of the filter mock feature. In contrast to the proposal in https://github.com/magnusbaeck/logstash-filter-verifier/issues/94#issuecomment-770877220 it was not possible to add the definition for the filter mocks into the test case file, because the mocks are needed to be applied to the "initial" config, which is loaded in the setup phase. Therefore I decided to put the mock filters into their own yaml config file, which can be specified optionally via command line flag.
Please merge #109 first.

Add filter mock

---

internal/app/app.go
internal/app/daemon_run.go
internal/daemon/session/session.go

* Fix handling of input codecs for cases, where multiple files contain input plugins
* Remove default value for --pipeline flag

Fix input codec and default value for --pipeline flag

---

internal/app/daemon/run/run.go
internal/daemon/pipeline/pipeline.go

* default value for --pipeline-base stays "" (empty string)
* if the config paths found in the pipelines.yml are absolute paths,
the pipeline base path setting is ignored.
* else (if the config paths found in the pipelines.yml are relative paths)
* if the pipeline base path is not set (this is, if it is the empty string ""),
the absolute path of the pipelines.yml file is used as the pipeline base path
(the assumption is, that relative paths in the pipelines.yml are relative to
the location of the file it self).
* if the pipeline base path is relative, it is converted to an absolute path by
prefixing it with the current working directory.
* if the pipeline base path is absolute, it is used as is.
the resulting absolute pipeline base path is prefixed to the relative config paths found in …

Fix how pipeline base path is determined

---

internal/daemon/instance/logstash/processors.go
internal/daemon/instance/logstash/processors_test.go
internal/daemon/pipeline/pipeline.go
internal/daemon/pipeline/pipeline_test.go
internal/daemon/pipeline/testdata/pipelines_basic_dir_name.yml
testdata/basic_pipeline_debug.yml
testdata/conditional_output.yml

* Fix pipeline id with dash
* Fix path.config pointing to dir in pipelines.yml
See also comments starting at https://github.com/magnusbaeck/logstash-filter-verifier/issues/93#issuecomment-913656206

Fix pipelines.yml issues

---

README.md
integration_test.go
internal/app/daemon/run/run.go
internal/app/daemon_run.go
internal/daemon/logstashconfig/file.go
internal/daemon/pipeline/pipeline.go
internal/daemon/pipeline/pipeline_test.go
internal/daemon/pluginmock/pluginmock.go
testdata/inputoutputmock.yml
testdata/inputoutputmock/main.conf
testdata/mocks/filtermock.yml
testdata/mocks/inputoutputmock.yml
testdata/testcases/inputoutputmock/testcase.json

In order to support isolated testing of Logstash configurations,
which use pipeline input and output plugins, the mocking is
extended to all types of plugins.
See also discussion: https://github.com/magnusbaeck/logstash-filter-verifier/issues/96#issuecomment-906726509

Support input & output plugins for mocking

---

internal/testcase/helper.go
internal/testcase/testcase_test.go
testdata/testcases/testcases_event/testcases_metadata_logstash.json
testdata/testcases/testcases_event/testcases_metadata_logstash_global.json
testdata/testcases/testcases_event/testcases_metadata_nested.json
testdata/testcases/testcases_event/testcases_metadata_nested_global.json
testdata/testcases_event/testcases_event.conf

Align bracket field regex with:
https://www.elastic.co/guide/en/logstash/current/field-references-deepdive.html#formal-grammar-field-name
https://github.com/elastic/logstash/blob/c698aa224b44c7356fbfeb58ebb0c4a66d72dc71/logstash-core/lib/logstash/config/grammar.treetop#L236
Fixes: #142

Align Logstash bracket field syntax with Logstash

---

.golangci.yml
Makefile

The new linters are reasonable and didn't require any changes to the existing code.

Upgrade golangci-lint and enable more linters

---

internal/app/app.go

With WARNING as the default loglevel the daemon wouldn't emit any useful status messages to let you know it has actually started up and is ready to be used. INFO will give users a few more messages overall but there's no dramatic increase and it's not likely to be regarded as spammy.

Change default loglevel from WARNING to INFO

---

internal/logstash/invocation.go

Fix the macos brew logstash'es configuration folder
Use additional folder relative to executable to cover another casees of  different logstash installation folder at different linux distributions and macos.
E.g./usr/local/bin/logstash with /usr/local/etc/logstash config folder as macos have

Add additional logstash configuration path

---

README.md

This entry was missing from commit e77dc8a where the section was added.

README.md: Add missing ToC entry for integration tests

---

internal/testcase/testcase_test.go

This unbreaks tests on systems where `/tmp` is linked to `/private/tmp`, for example.
```
2024/06/24 13:49:31 --- FAIL: TestNewFromFile (0.00s)
2024/06/24 13:49:31     testcase_test.go:141: Expected test case path to be "/tmp/TestNewFromFile730042975/001/filename.json", got "/private/tmp/TestNewFromFile730042975/001/filename.json" instead.
2024/06/24 13:49:31 FAIL
```

Resolve symlinks to make test more portable.

---

internal/testcase/helper.go
internal/testcase/testcase.go
internal/testcase/testcase_test.go

Found this while working on #97. Contrary to the documentation, using bracket field references in the testcases array didn't actually work. The substitution only took place for the now-deprecated "input" key. In other words,
codec: json_lines
input:
- '{"[foo][bar]": "value"}'
worked as expected, but
codec: json_lines
testcases:
input: - '{"[foo][bar]": "value"}'
didn't. This has been addressed so that the "input" arrays work the same in both places.

internal/testcase: Support bracket field references for testcases

---

Makefile

With the toolchain support added in Go 1.21 there's hardly any need to build the release tarballs via a Docker container with the desired Go version. Apart from getting rid of an unnecessary dependency, the release-tarballs target started working a while back when Git started complaining about .git directories with the wrong owner, resulting in the following error message:
failed to collect values: failed to get commit: git: error="exit status 128" stderr=fatal: detected dubious ownership in repository at '<DIR>/logstash-filter-verifier'

Makefile: Stop building release tarballs with Docker

---

Makefile

It's hard to imagine anyone running LFV on 32-bit x86. Make sure we provide binaries for modern Macs instead.

Makefile: Build binaries for darwin_arm64 instead of linux_386
